# Generated by Django 5.2 on 2025-07-16 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 14, 29, 26, 95246, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
