# Generated by Django 5.2 on 2025-07-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='directions',
            new_name='instructions',
        ),
    ]
